baseURL: /
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableEmoji: true
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
imaging:
  anchor: smart
  quality: 75
  resampleFilter: CatmullRom
languages:
  en:
    languageCode: en
    languageName: English
    time_format_blog: 2006-01-02
    time_format_default: 2006-01-02
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: friendly
  parser:
    autoHeadingID: true
    autoHeadingIDType: github
module:
  hugoVersion:
    extended: true
  imports:
  - disable: false
    path: github.com/google/docsy
  - disable: false
    path: github.com/google/docsy/dependencies
  proxy: direct
outputs:
  home:
  - HTML
  page:
  - HTML
params:
  algolia_docsearch: false
  copyright: Keptn Community
  description: Cloud-native application life-cycle orchestration
  github_branch: main
  github_project_repo: https://github.com/keptn/lifecycle-toolkit
  github_repo: https://github.com/keptn-sandbox/lifecycle-toolkit-docs
  links:
    developer:
    - desc: Development takes place here!
      icon: fab fa-github
      name: GitHub
      url: https://github.com/keptn/lifecycle-toolkit
    - desc: Chat with other project developers
      icon: fab fa-slack
      name: Slack
      url: https://cloud-native.slack.com/messages/keptn
    - desc: Watch videos about Keptn
      icon: fab fa-youtube
      name: Keptn YouTube channel
      url: https://youtube.com/@keptn
    user:
    - desc: Follow us on Twitter to get the latest news!
      icon: fab fa-twitter
      name: Twitter
      url: https://twitter.com/KeptnProject
    - icon: fab fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/company/keptnproject
  markmap:
    enable: true
  offlineSearch: true
  slack: https://cloud-native.slack.com/messages/keptn
  taxonomy:
    pygmentsCodeFences: true
    pygmentsUseClasses: true
    pygmentsUseClassic: false
    taxonomyCloud:
    - tags
    - categories
    taxonomyCloudTitle:
    - tags
    - categories
    taxonomyPageHeader:
    - tags
    - categories
  ui:
    breadcrumb_disable: false
    footer_about_disable: false
    header_search_disable: true
    navbar_logo: true
    sidebar_menu_compact: true
    sidebar_menu_foldable: true
    sidebar_menu_truncate: 1000
    sidebar_search_disable: false
  url_latest_version: https://lifecycle.keptn.sh
  version: 0.5.0
  version_menu: Releases
  versions:
  - url: /docs-0.5.0/
    version: 0.5.0
  - url: /docs-0.4.1/
    version: 0.4.1
  - url: /docs-dev/
    version: dev
permalinks: blog = "/:section/:year/:month/:day/:slug/"
taxonomies:
  category: categories
  tag: tags
title: keptn
